name: "about me"
output_dir:
navbar: 
  title: "Caitlin's GitHub Pages"
  left:
  - text: "Home"
   href: index.html
  - text: "About me"
   href: caitlin-about-me.html
output:
  html_document:

theme: jekyll-theme-modernist